### ISSUE TITLE
Only workspace gets exported to the folder

### ISSUE THREAD

**Issue by ogisandev** [rojo-rbx/rbxlx-to-rojo#61] opened 2022-07-07 17:40 UTC
![image](https://user-images.githubusercontent.com/108893760/177835719-857548ee-a22c-4df2-84e0-46958515a64d.png)
![image](https://user-images.githubusercontent.com/108893760/177835757-d86633c4-dd03-4627-a38e-bb46a737cc6c.png)
After converting the place, only workspace gets converted to rojo.

Also some warnings come up in the converting process, I don't know if it has to do anything with this.

![image](https://user-images.githubusercontent.com/108893760/177835976-ce07e67e-ee6a-4de3-8eb2-c6a9df1cad2b.png)

**Comment by Kampfkarren** [comment] 2022-07-07 21:01
rbxlx-to-rojo is instantly closing before it can get more errors. This is a bug but it's a known one. 

Run it with PowerShell to see the issue. The issue is usually that you have a folder or script name with a character Windows doesn't like. Make sure all your names are only letters, numbers, spaces, and underscores.

**Closed as not planned by Kampfkarren** 2022-07-07 21:01 UTC
