### ISSUE TITLE
Is it broken ? Program killed after selecting my .rblx file

### ISSUE THREAD

**Issue by hugoderre** [rojo-rbx/rbxlx-to-rojo#66] opened 2022-10-26 00:29 UTC
Since yesterday, I can no longer extract folder/files from .rblx files.
When I run the program and select my .rblx file, the program is directly killed. I can't see the error.
Anyone has the same issue? It's maybe broken because of roblox studio update? Or it's just from my side.

**Comment by Kampfkarren** [comment] 2022-10-26 00:50
rbxlx-to-rojo is instantly closing before it can get more errors. This is a bug but it's a known one.

Run it with PowerShell to see the issue. The issue is usually that you have a folder or script name with a character Windows doesn't like. Make sure all your names are only letters, numbers, spaces, and underscores.

**Comment by hugoderre** [comment] 2022-10-26 01:14
I opened it and executed with Powershell and here is the output:

``[2022-10-26T00:54:48Z WARN  rbx_binary::deserializer] Unknown value type ID 0x1f (31) in Roblox binary model file. Found in property AnalyticsService.UniqueId.``
``[2022-10-26T00:54:48Z WARN  rbx_binary::deserializer] Unknown value type ID 0x1e (30) in Roblox binary model file. Found in property Model.WorldPivotData..``
``An error occurred while using rbxlx-to-rojo..``
``While attempting to decode the place file, at stream did not contain valid UTF-8 rbx_binary didn't know what to do``

**Comment by hugoderre** [comment] 2022-10-26 01:15
Ok I have deleted all the elements in the workspace and it's working. I will investigate, thanks for your help!

**Closed as completed** 2022-10-26 01:15 UTC

**Comment by hugoderre** [comment] 2022-10-26 01:23
![Capture](https://user-images.githubusercontent.com/50342575/197912384-42095f5c-adfa-42ad-be27-e1a67f4c79e9.PNG)
You were right.
